config/routes.rb
Rails.application.routes.draw do
  resources :media
  resources :achievements
  resources :evidences
  resources :reviews
  resources :users
  resources :promises
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/evidence.rb
class Evidence < ApplicationRecord
  belongs_to :promise
  belongs_to :user
  has_many :medium
  has_many :reviews
  has_one :achievement
end

app/controllers/evidences_controller.rb
class EvidencesController < ApplicationController
  before_action :set_evidence, only: %i[ show edit update destroy ]

  # GET /evidences or /evidences.json
  def index
    @evidences = Evidence.all
  end

  # GET /evidences/1 or /evidences/1.json
  def show
  end

  # GET /evidences/new
  def new
    @evidence = Evidence.new
  end

  # GET /evidences/1/edit
  def edit
  end

  # POST /evidences or /evidences.json
  def create
    @evidence = Evidence.new(evidence_params)

    respond_to do |format|
      if @evidence.save
        format.html { redirect_to evidence_url(@evidence), notice: "Evidence was successfully created." }
        format.json { render :show, status: :created, location: @evidence }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @evidence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evidences/1 or /evidences/1.json
  def update
    respond_to do |format|
      if @evidence.update(evidence_params)
        format.html { redirect_to evidence_url(@evidence), notice: "Evidence was successfully updated." }
        format.json { render :show, status: :ok, location: @evidence }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @evidence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evidences/1 or /evidences/1.json
  def destroy
    @evidence.destroy

    respond_to do |format|
      format.html { redirect_to evidences_url, notice: "Evidence was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evidence
      @evidence = Evidence.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def evidence_params
      params.require(:evidence).permit(:name, :content)
    end
end

app/helpers/evidences_helper.rb
module EvidencesHelper
end

app/views/evidences/_evidence.html.erb
<div id="<%= dom_id evidence %>">
  <p>
    <strong>Name:</strong>
    <%= evidence.name %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= evidence.content %>
  </p>

</div>

app/views/evidences/_form.html.erb
<%= form_with(model: evidence) do |form| %>
  <% if evidence.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(evidence.errors.count, "error") %> prohibited this evidence from being saved:</h2>

      <ul>
        <% evidence.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/evidences/edit.html.erb
<h1>Editing evidence</h1>

<%= render "form", evidence: @evidence %>

<br>

<div>
  <%= link_to "Show this evidence", @evidence %> |
  <%= link_to "Back to evidences", evidences_path %>
</div>

app/views/evidences/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Evidences</h1>

<div id="evidences">
  <% @evidences.each do |evidence| %>
    <%= render evidence %>
    <p>
      <%= link_to "Show this evidence", evidence %>
    </p>
  <% end %>
</div>

<%= link_to "New evidence", new_evidence_path %>

app/views/evidences/new.html.erb
<h1>New evidence</h1>

<%= render "form", evidence: @evidence %>

<br>

<div>
  <%= link_to "Back to evidences", evidences_path %>
</div>

app/views/evidences/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @evidence %>

<div>
  <%= link_to "Edit this evidence", edit_evidence_path(@evidence) %> |
  <%= link_to "Back to evidences", evidences_path %>

  <%= button_to "Destroy this evidence", @evidence, method: :delete %>
</div>