config/routes.rb
Rails.application.routes.draw do
  resources :media
  resources :achievements
  resources :evidences
  resources :reviews
  resources :users
  resources :promises
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :user
  belongs_to :promise
  has_many :reviews
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :set_achievement, only: %i[ show edit update destroy ]

  # GET /achievements or /achievements.json
  def index
    @achievements = Achievement.all
  end

  # GET /achievements/1 or /achievements/1.json
  def show
  end

  # GET /achievements/new
  def new
    @achievement = Achievement.new
  end

  # GET /achievements/1/edit
  def edit
  end

  # POST /achievements or /achievements.json
  def create
    @achievement = Achievement.new(achievement_params)

    respond_to do |format|
      if @achievement.save
        format.html { redirect_to achievement_url(@achievement), notice: "Achievement was successfully created." }
        format.json { render :show, status: :created, location: @achievement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /achievements/1 or /achievements/1.json
  def update
    respond_to do |format|
      if @achievement.update(achievement_params)
        format.html { redirect_to achievement_url(@achievement), notice: "Achievement was successfully updated." }
        format.json { render :show, status: :ok, location: @achievement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /achievements/1 or /achievements/1.json
  def destroy
    @achievement.destroy

    respond_to do |format|
      format.html { redirect_to achievements_url, notice: "Achievement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_achievement
      @achievement = Achievement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def achievement_params
      params.require(:achievement).permit(:money)
    end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/views/achievements/_achievement.html.erb
<div id="<%= dom_id achievement %>">
  <p>
    <strong>Money:</strong>
    <%= achievement.money %>
  </p>

</div>

app/views/achievements/_form.html.erb
<%= form_with(model: achievement) do |form| %>
  <% if achievement.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(achievement.errors.count, "error") %> prohibited this achievement from being saved:</h2>

      <ul>
        <% achievement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :money, style: "display: block" %>
    <%= form.text_field :money %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/achievements/edit.html.erb
<h1>Editing achievement</h1>

<%= render "form", achievement: @achievement %>

<br>

<div>
  <%= link_to "Show this achievement", @achievement %> |
  <%= link_to "Back to achievements", achievements_path %>
</div>

app/views/achievements/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Achievements</h1>

<div id="achievements">
  <% @achievements.each do |achievement| %>
    <%= render achievement %>
    <p>
      <%= link_to "Show this achievement", achievement %>
    </p>
  <% end %>
</div>

<%= link_to "New achievement", new_achievement_path %>

app/views/achievements/new.html.erb
<h1>New achievement</h1>

<%= render "form", achievement: @achievement %>

<br>

<div>
  <%= link_to "Back to achievements", achievements_path %>
</div>

app/views/achievements/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @achievement %>

<div>
  <%= link_to "Edit this achievement", edit_achievement_path(@achievement) %> |
  <%= link_to "Back to achievements", achievements_path %>

  <%= button_to "Destroy this achievement", @achievement, method: :delete %>
</div>